version: 2

project_name: diskio

before:
  hooks:
    - go mod tidy
    

builds:
  - id: diskio
    main: ./backend/main.go
    binary: diskio
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    hooks:
      pre: 
      - cmd: "scripts/build-frontend.sh"

upx:
  - enabled: true
    compress: best
    brute: true

checksum:
  disable: true

changelog:
  disable: false
  use: github   # 也可以改成 git 或 github，区别见文末备注

  title: "Release Notes"
  groups:
    - title: Features
      regexp: "^feat.*"
      order: 0
    - title: Bug fixes
      regexp: "^fix.*"
      order: 1
    - title: Code refacotoring
      regexp: "^refactor.*"
      order: 2

  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^docs:"

# release:
#   disable: true