version: 2

project_name: diskio

before:
  hooks:
    - go mod tidy

builds:
  - id: diskio
    main: ./src/main.go
    binary: diskio
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w

upx:
  - enabled: true
    compress: best
    brute: true

archives:
  - format: binary
checksum:
  disable: true
changelog:
  disable: true
# release:
#   disable: true