version: 2

project_name: diskio

before:
  hooks:
    - go mod tidy
    

builds:
  - id: diskio
    main: ./backend/main.go
    binary: diskio
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    hooks:
      pre: 
      - cmd: "scripts/build-frontend.sh"

upx:
  - enabled: true
    compress: best
    brute: true

checksum:
  disable: true
changelog:
  disable: true
# release:
#   disable: true