version: 2

project_name: diskio

before:
  hooks:
    - go mod tidy
    - scripts/build-frontend.sh
    

builds:
  - id: diskio
    main: ./backend/main.go
    binary: diskio
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
        
archives:
  - formats: ["binary"]

upx:
  - enabled: true
    compress: best
    brute: true

checksum:
  disable: true

changelog:
  use: github

  groups:
    - title: Features
      regexp: "^feat.*"
      order: 0
    - title: Bug fixes
      regexp: "^fix.*"
      order: 1
    - title: Code refacotoring
      regexp: "^refactor.*"
      order: 2

  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^docs:"

# release:
#   disable: true